[package]
name = "notifier"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
discord.workspace = true
shared.workspace = true
manga.workspace = true
registry.workspace = true
tokio.workspace = true