mangas:
  - title: "最強出涸らし皇子の暗躍帝位争い"
    short_title: "degarashi"
    url: "https://web-ace.jp/youngaceup/contents/1000137/"
  - title: "不遇職【鑑定士】が実は最強だった～奈落で鍛えた最強の【神眼】で無双する～"
    short_title: "kanteishi_saikyo"
    url: "https://pocket.shonenmagazine.com/episode/13933686331683386618"
  - title: "ドローイング 最強漫画家はお絵描きスキルで異世界無双する！"
    short_title: "drawing"
    url: "https://comic-valkyrie.com/drawing/"
  - title: "四度目は嫌な死属性魔術師"
    short_title: "yondome"
    url: "https://comic-walker.com/detail/KC_003524_S?episodeType=latest"
  - title: "RTA走者はゲーム世界から帰れない"
    short_title: "rta_kaerenai"
    url: "https://comic-walker.com/detail/KC_003956_S/episodes/KC_0039560002000011_E?episodeType=latest"
  - title: "ワンパンマン"
    short_title: "one_punch_man"
    url: "https://tonarinoyj.jp/episode/13932016480028985383"
  - title: "漫画版クウガ"
    short_title: "kuga"
    url: "https://viewer.heros-web.com/episode/10834108156632483750"
  - title: "ファイアーエムブレム エンゲージ"
    short_title: "fe_engage"
    url: "https://shonenjumpplus.com/episode/4856001361004111261"
  - title: "魔都精兵のスレイブ"
    short_title: "matoseihei"
    url: "https://shonenjumpplus.com/episode/10834108156641784254"
  - title: "とある暗部の少女共棲"
    short_title: "toaru_anbu"
    url: "https://comic-walker.com/detail/KC_000597_S?episodeType=latest"
  - title: "転生コロシアム"
    short_title: "tensei_coliseum"
    url: "https://comic-walker.com/detail/KC_001662_S/episodes/KC_0016620002600031_E?episodeType=latest"
  - title: "年上エリート女騎士が僕の前でだけ可愛い"
    short_title: "elder_elite"
    url: "https://web-ace.jp/youngaceup/contents/1000134/"
  - title: "魔王学園の反逆者"
    short_title: "maou_rebellion"
    url: "https://comic-walker.com/detail/KC_000615_S?episodeType=latest"
  - title: "ゲームオブファミリア"
    short_title: "game_of_familia"
    url: "https://comic-walker.com/detail/KC_005141_S?episodeType=latest"
  - title: "回復術士のやり直し"
    short_title: "kaihuku_jutsushi"
    url: "https://web-ace.jp/youngaceup/contents/1000049/"
  - title: "サタノファニ"
    short_title: "satanophany"
    url: "https://yanmaga.jp/comics/%E3%82%B5%E3%82%BF%E3%83%8E%E3%83%95%E3%82%A1%E3%83%8B"
  - title: "戦隊タブー"
    short_title: "sentai_taboo"
    url: "https://comic-days.com/episode/2550689798543753536"
